### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by markwwen** [cure-lab/sat-benchmark#1]
It is very amazing that someone starts to build a benchmark/framework for ML/AI for SAT, which would be very helpful for the new people who is just entering this area like me. 
Here are some doc/tools I think maybe useful, the author can have a look in free time:
- [awesome-ml4co](https://github.com/Thinklab-SJTU/awesome-ml4co#boolean-satisfiability) The Boolean Satisfiability collect some recent papers in ML4SAT.
- [LovaszSAT](https://github.com/HughWen/LovaszSAT) A tool by me which implements the Algorithmic LLL Solver, the [generator.py](https://github.com/HughWen/LovaszSAT/blob/main/generator.py) can be use to generate large satisfiable SAT instance quickly, which maybe useful in building dataset.

**Comment by lee-man** [comment]
Thanks for your attention! This codebase is not ready to use yet, and I will let you know once we complete it. I will take a look at your repo and have further discussion with you later :)
